name = "multi-time-link-opener"
main = "src/index.js"
compatibility_date = "2024-12-18"

[vars]
MAX_TEST_COUNT = 500
REQUEST_TIMEOUT_MS = 15000
RATE_LIMIT_PER_MINUTE = 35
ALLOWED_HOSTS = "*"

[env.production.vars]
MAX_TEST_COUNT = 500
REQUEST_TIMEOUT_MS = 15000
RATE_LIMIT_PER_MINUTE = 35
ALLOWED_HOSTS = "*"
